config/routes.rb
Rails.application.routes.draw do
  resources :histoires
  resource :accueil
  root "accueil#index"
  devise_for :auteurs, controllers: { confirmations: 'confirmations' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auteur.rb
class Auteur < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :omniauthable, omniauth_providers: %i[facebook]
end

app/models/histoire.rb
class Histoire < ApplicationRecord
end

app/controllers/accueil_controller.rb
class AccueilController < ApplicationController
  before_action :authenticate_auteur!#, except: [:index]
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
    private
    def after_confirmation_path_for(resource_name, resource)
      sign_in(resource) # In case you want to sign in the user
      histoires_path
    end
  end

app/controllers/histoires_controller.rb
class HistoiresController < ApplicationController
  before_action :set_histoire, only: [:show, :edit, :update, :destroy]

  # GET /histoires
  # GET /histoires.json
  def index
    @histoires = Histoire.all
  end

  # GET /histoires/1
  # GET /histoires/1.json
  def show
  end

  # GET /histoires/new
  def new
    @histoire = Histoire.new
  end

  # GET /histoires/1/edit
  def edit
  end

  # POST /histoires
  # POST /histoires.json
  def create
    @histoire = Histoire.new(histoire_params)

    respond_to do |format|
      if @histoire.save
        format.html { redirect_to @histoire, notice: 'Histoire was successfully created.' }
        format.json { render :show, status: :created, location: @histoire }
      else
        format.html { render :new }
        format.json { render json: @histoire.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /histoires/1
  # PATCH/PUT /histoires/1.json
  def update
    respond_to do |format|
      if @histoire.update(histoire_params)
        format.html { redirect_to @histoire, notice: 'Histoire was successfully updated.' }
        format.json { render :show, status: :ok, location: @histoire }
      else
        format.html { render :edit }
        format.json { render json: @histoire.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histoires/1
  # DELETE /histoires/1.json
  def destroy
    @histoire.destroy
    respond_to do |format|
      format.html { redirect_to histoires_url, notice: 'Histoire was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_histoire
      @histoire = Histoire.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def histoire_params
      params.require(:histoire).permit(:titre, :contenu)
    end
end

app/helpers/accueil_helper.rb
module AccueilHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/histoires_helper.rb
module HistoiresHelper
end

app/views/accueil/index.html.erb
<div class="container-fluid bg-primary">
    <div class="row">
        <div class="col-xl-6">
            <h1>
            Si vous pensez que les histoires ne sont pas importantes, 
            attendez jusqu'à ce qu'elles soient tout ce que vous laisserez derrière vous !
            </h1>
            <p>
                Que ce soit pour inspirer, motiver, conseiller ou juste pour marquer
                votre passage sur terre, nous vous permettons d'écrire vos histoires.
            </p>
            <a class="btn btn-light" href="#">
            Je veux ommencer à écrire des histoires
            </a>  
        </div>
        <div class="col-xl-6">
            
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-xl-12">
            <p>Tendances sur Eritage</p>   
        </div>
    </div>
</div>

app/views/auteurs/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/auteurs/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/histoires/_form.html.erb
<%= form_with(model: histoire, local: true) do |form| %>
  <% if histoire.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(histoire.errors.count, "error") %> prohibited this histoire from being saved:</h2>

      <ul>
        <% histoire.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titre %>
    <%= form.text_field :titre %>
  </div>

  <div class="field">
    <%= form.label :contenu %>
    <%= form.text_area :contenu %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/histoires/edit.html.erb
<h1>Editing Histoire</h1>

<%= render 'form', histoire: @histoire %>

<%= link_to 'Show', @histoire %> |
<%= link_to 'Back', histoires_path %>

app/views/histoires/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Histoires</h1>

<table>
  <thead>
    <tr>
      <th>Titre</th>
      <th>Contenu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @histoires.each do |histoire| %>
      <tr>
        <td><%= histoire.titre %></td>
        <td><%= histoire.contenu %></td>
        <td><%= link_to 'Show', histoire %></td>
        <td><%= link_to 'Edit', edit_histoire_path(histoire) %></td>
        <td><%= link_to 'Destroy', histoire, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Histoire', new_histoire_path %>

app/views/histoires/new.html.erb
<h1>New Histoire</h1>

<%= render 'form', histoire: @histoire %>

<%= link_to 'Back', histoires_path %>

app/views/histoires/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titre:</strong>
  <%= @histoire.titre %>
</p>

<p>
  <strong>Contenu:</strong>
  <%= @histoire.contenu %>
</p>

<%= link_to 'Edit', edit_histoire_path(@histoire) %> |
<%= link_to 'Back', histoires_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eritage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>